### ISSUE TITLE
Upload docker image to other platform

### ISSUE THREAD

**Issue by g2asell2019** [2833844911/passja3#1]
Hi, I appreciate your project a lot but unfortunate I can't docker image because I can't create baidu account

Can you upload docker image to [dockerhub](https://hub.docker.com/)?

Thank you very much.

**Comment by 2833844911** [comment]
you can down of https://drive.google.com/file/d/1apHnsBal4Lzhs8iajqB4ay-DGtHstceO/view?usp=sharing

**Comment by g2asell2019** [comment]
I appreciate your efforts a lot.

After download docker image, I run it on github codespace

here is my webserver: 
![image](https://github.com/user-attachments/assets/713f8ec9-1152-431b-878f-0f38a1133533)

this is my docker command: 
![image](https://github.com/user-attachments/assets/3d9c21fc-3847-4633-9c9c-d2adf72d2d10)
![image](https://github.com/user-attachments/assets/6166d005-94ec-40a0-9c10-d64bd16d0c28)

Test result: example from [this](https://github.com/2833844911/passja3/blob/0dba28637c402cc2dfeb6b7a84fb7a3516bf1bd3/README.md?plain=1#L9)
![image](https://github.com/user-attachments/assets/29588f2e-434a-44df-b24d-1894de3b9640)

Then I inspect the docker image, I found there is no expose port command related to the port use on `ud` url to map to it
![image](https://github.com/user-attachments/assets/0cd6fc2f-faa4-4ddf-afe5-3264ad306290)
![image](https://github.com/user-attachments/assets/0332489c-66d0-476e-a820-77c47a48b78e)

Can you help me shed a light on this problem? Perhaps can you share your .Dockerfile so I can re-build the image then report to you later?

Thank you very much!!

**Comment by 2833844911** [comment]
The previous version was uploaded incorrectly
https://drive.google.com/file/d/1zSs0kSZO3NE_-OJDF7UkLRMBUR5Lc9PR/view?usp=sharing
This is the official version

**Comment by 2833844911** [comment]
![image](https://github.com/user-attachments/assets/667f3cc9-8b50-44a8-8825-ae5a2e161f80)
use your ip:port

**Comment by 2833844911** [comment]
Can you try requesting this URL
https://tls.peet.ws/api/all


from cytls import cytls

headers ={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
}


proxies =  {"https": "http://proxyip:proxyport"}

url ="https://tls.peet.ws/api/all"
req = cytls.get(url, headers=headers, proxies=proxies)


dt = req.text
print(req.status_code)
print(req.headers)
print(req.cookies)
print(dt)

**Comment by g2asell2019** [comment]
After diving a bit deeper this is what I found:

- I can assert that port `6000` and `8080` is indeed listen on request
```bash
root@fc17e0c804c3:/home# /usr/local/bin/main
cbb zf tool
:
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /request                  --> main.startds.func1 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
[GIN-debug] [ERROR] listen tcp :8080: bind: address already in use
2024/07/15 06:47:56 listen tcp :6000: bind: address already in use
```
there seems to be mismatch port on docker

**Comment by g2asell2019** [comment]
> Can you try requesting this URL
> https://tls.peet.ws/api/all

I got this working after update to your lastest docker image

![image](https://github.com/user-attachments/assets/68e2d657-334e-440e-afad-dca6e3dd47f2)

**Comment by 2833844911** [comment]
The 6000 port is a test version, and 8081 is the official version
This is the official version of the image
https://drive.google.com/file/d/1zSs0kSZO3NE_-OJDF7UkLRMBUR5Lc9PR/view?usp=sharing
